Account for non-standard post type menu locations
mrwweb/post-type-archive-descriptions pull request #10
Opened 2020-04-16 00:32 UTC by eyesofjeremy

Since a post type can be registered with a non-standard location, it seems reasonable to account for this by setting up a function to check for the post type's `show_in_menu` setting. If it's set to a specific location, the modified plugin will use that for the parent location.

At that point, the $_GET['post_type'] parameter may not be reflective of the correct post type, but the $_GET['page'] parameter is generated by the plugin, so we use that as a reference for generating the appropriate metabox.

This addresses issue #9. It has not been extensively tested yet.

2020-04-16 15:04 UTC, mrwweb commented
Thanks for this, @eyesofjeremy. It's gonne be a week or two before I can get to this, but I am extremely appreciative and don't want to let this sit too long.

Would you be willing to share your post type registration code so I can test against your exact setup? I've never worked on a site quite like that, so I'd love to make sure I'm looking at the same thing you are.

2020-04-16 16:26 UTC, eyesofjeremy commented
Sure, here is a test case plugin that sets up the post types per my site's needs.

[gtt.1.8.ptad.zip](https://github.com/mrwweb/post-type-archive-descriptions/files/4488493/gtt.1.8.ptad.zip)

Let me know if you need anything else. Thanks!

2020-05-11 17:05 UTC, eyesofjeremy commented
Hi there,

My client found an issue — the Admin Bar link showing up on the Archive page was not accounting for the changed address. I've added a commit which fixes this, plus fixing an incorrect comment on a new filter, and a couple of version bumps for tracking (using the beta version on the client's live site.)

Best,
Jeremy

2020-08-08 18:45 UTC, mrwweb requested changes
@eyesofjeremy Thank you so much again for submitting this, and sorry that it took me so long to get this. I appreciate your work to make this plugin more flexible and this will definitely get incorporated. I flagged a few issues I'd love to tweak. Do you want to make these changes or would you prefer I do it? Don't want to step on your toes, but also realize it took me forever to get to this. I'll accept the PR and tweak further myself if I don't hear from you in a week or so.

2020-08-08 18:45 UTC, mrwweb commented on post-type-archive-descriptions.php
> +	$page = $_GET['page'];
This method of determining the post type should work for both top-level and nested admin pages, so I'm tempted to remove the check and then just use the `$_GET[]` var. Any objections?

2020-08-08 18:45 UTC, mrwweb commented on post-type-archive-descriptions.php
> +				// Check if post type has a particular parent menu location
extra indent on these four lines

2020-08-08 18:45 UTC, mrwweb commented on post-type-archive-descriptions.php
> +function ptad_settings_page_parent( $post_type, $show_in_menu = false ) {
`$show_in_menu` needs documentation. The name is a little odd in this context even though I realize it's coming straight from the WP naming conventions. It's tempting to give it a different name, but that might just confuse things further.

2020-08-08 18:45 UTC, mrwweb commented on post-type-archive-descriptions.php
> +			'href'  => admin_url( $parent_page . '&page=' . $post_type . '-description' )
Just a note that the admin bar link (starting on Line 383) in the Admin (goes from description edit page to post type archive) is broken for nested post type menu items. Can be fixed later.

2020-10-03 21:02 UTC, merged

2020-10-03 22:26 UTC, mrwweb commented
@eyesofjeremy Thanks again for your contribution! v1.2.0 was just released including your fixes 😃

If you have a wordpress.org username, please let me know so I can add you as a contributor to the plugin!

2020-10-06 19:30 UTC, eyesofjeremy commented
Hi @mrwweb sorry I didn't get back to you earlier, looks like you had a couple more tweaks in there. Happy to be listed as a contributor :) username is jcdesign on WP.org.

2020-10-11 18:11 UTC, mrwweb commented
No problem! Just added you and it should show up shortly :)